------------------------------------------------------------------------

title: "Pertemauaan1" output: html_notebook --- Nama : Jean Probosky Ginting Nim : 200803078

# Pertemuan1

## Assigment dalam r mendefinisikan `variabel` dengan assigment berikut :

### RA

```{r}
a=1
a<-1
1->a
print(a)


```

## Vektor

```{r}
vectior=c(1,2,3,4,5)
print(vectior)

```

### Operasi Aritmatika

```{r}
5+2
5-2
5*2
5/2
m=2
c=3
print(m+c)
print (m-c)
print (m*c)
print (m/c)


```

## Modulo(Sisa Bagi)

```{r}
5%%2
```

## oPERATOR logika

```{r}
1&&1
1&0
0&1
0&0
10&&10
10&&0
T&&T
T&&F
T ||T
T || F
F || T
F || F
```

**F0303HGSGSGSGXIAJAMEILY** \### Pertemuan 3 \### Operator Perbandingan

```{r}
1==0
1!=0
1>=0
1>0
1<0
print(1<=0)

```

```{r}


```

#### Sequence and Matrix

```{r}
barisAN1 = 1:10
barisan2 = seq(1,10)
print(barisAN1)
print (barisan2)
barisAN1 == barisan2
barisan3= seq(1,10,2)
print (barisan3)
print (barisan3[1]) ##indeks 3
print (barisAN1[8]) ##indeks 8
print (barisan3[c(1,3,5)])
```

```{r}
barisan4 =seq (1,100,3)
print(barisan4)
print (length(barisan4))
print (barisan4[seq(2,34,2)])
print (barisan4[seq(1,34,2)])
```
### Matriks
```{r}
data=c(20,30,40,50)
matrix(data=data, nrow=2, ncol=2)
matrix(data, nrow=2, ncol=2,byrow =TRUE)
x = 1:20
print(x)
matrix(x, nrow=4, ncol=5,byrow =TRUE)
```


