---
title: "Pertemuan 1 dan 2"
output: html_notebook
---

Nama : Rahmadani

Nim : 200803030 \# Pertemuan 1

## Assignment

dalam R kita bisa membuat variabel atau mendefinisikan sebuah variabel dengan assignment seperti berikut : '''{r}

a = 1;

a \<- 1;

1-\> a;

print(a)

## Vector

```{r}
vektor1 <- c(1,2,3,4,5)
print(vektor 1)

```

### Penjumlahan

```{r}
5+2 
print 
```

### Pengurangan

```{r}
5-2
```

### Perkalian

```{r}
5 * 3
```

### Pembagian

```{r}
 5/2
```

### Modulo (Sisa Bagi)

```{r}
5%%2
```

### AND(DAN)

```{r}
T && T
1 && 1
-1 && -1
0 && 0

```

```{r}
1 || 1
1 || 0
0 || 1
0 || 0


```

```{r}
! (1)
```

## Pertemuan 3

### Operator Pembanding

```{r}
print(1 == 0) # apakah 1 sama dengan 0?
print (1!=0) # apakah 1 tidak sama dengan 0?
print (1 > 0) # apakah 1 lebih besar 0?
print (1>=0) # apakah 1 lebih besar  atau sama dengan 0?
print (1<0)  # apakah 1 lebih kecil 0?
print (1<=0) # apakah 1 lebih kecil atau sama dengan 0?
```

!(25 && -1) \|\| ((19\>9) && (0 \|\| 1))

```{r}
!(25 && -1) || ((19>9) && (0 || 1))
```

### Sequence dan Matrix

```{r}
barisan1 = 1:10
barisan2 = seq (1,10)
print(barisan1)
print(barisan2)
barisan1 == barisan2
barisan3 = seq (1,10,2)
print(barisan3)
print(barisan3 [4]) ## index 4 di barisan3 = 7
print(barisan3 [1])  ## index 3 di barisan3 = 1
print(barisan3 [c(3,4)])  ## index 3 dan 4 di barisan3 = 5 7
```

```{r}
barisan4 = seq(1,100,3)
print(barisan4)
print(barisan4[seq(2, 34,2)])
```


### Matriks 
```{r}
data = c(20,30,40,50)
matrix(data = data, nrow = 2 , ncol = 2)
matrix(data = data, nrow = 2 , ncol = 2,byrow = TRUE)
```
```{r}
x = 1:20
matrix(data = data, nrow = 4 , ncol = 5,byrow = TRUE)
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```

