---
title: "Pertemuan 1 dan 2"
output: html_notebook
---

Nama : Alpontura Siregar
NIM  : 200803058

# Pertemuan 1

## Assignment

Dalam R kita bisa membuat atau mendefinisikan sebuah variabel dengan assignment sebagai berikut:

```{r}
a=1;
a<-1;
1->a;
print(a)
```

**Vector**

```{r}
vector1 <- c(1,2,3,4,5)
print(vector1)
```

# Operator

## Penjumlahan

```{r}
1+2;
print(1+2)
```

## Pengurangan

```{r}
3-2;
print(3-2)

```

## Perkalian

```{r}
5*3

```

```{r}
1 && 1
0 && 0
2 && 3
5 && -5
F && F
```

```{r}
1 || 1
1 || -1
-1 || -1
-1 || 0
0 || 0
```
## Pertemuan 3
### Operator Perbandingan

```{r}
print (1==0)  #apakah 1 sama dengan 0?
print (1!=0)  #apakah 1 tidak sama dengan 0?
print (1>0)   #apakah 1 lebih besar 0?
print (1>= 0) #apakah 1 lebih besar atau sama dengan 0?
print (1< 0)  #apakah 1 lebih kecil 0?
print (1<=0)  #apakah 1 lebih kecil atau sama dengan 0?

```
```{r}
!(25&&-1) || ((19>9)) && (0||1)
```


### Sequence dan Matrix 
```{r}
barisan1 = 1:10
barisan2 = seq(1,10)
print (barisan1)
print (barisan2)
barisan1 == barisan2
barisan3 = seq(1,10,2)
print(barisan3)
print(barisan3 [4])
```
## Cara mengambil elemen pada vector
```{r}
print(barisan3)
print(barisan3 [1]) ##indeks 1 di barisan3 = 1 
print(barisan3 [4]) ##indeks 4 di barisan3 = 7
print(barisan3 [c(3,4)]) ##indeks 3 dan 4 dibarisan3 = 5 dan 7
```
```{r}
barisan4 = seq(1,100,3)
print(barisan4)
n = length(barisan4)
print(n)
print(barisan4[seq(3,n,2)])
```
### Matriks
```{r}
data=c(20,30,40,50)
matrix(data=data, nrow=2, ncol=2)
matrix(data=data, nrow=2, ncol=2, byrow=TRUE)
```



```{r}
data=1:20
matrix(data=data, nrow=4, ncol=5, byrow=TRUE)
```









