---
title: "Pertemuan 1 dan 2"
output: html_notebook
---

Nama : Fidelia Aprilia Emelia Tamba
NIM  : 200803012

# Pertemuan 1

## Assignment

Dalam R kita bisa membuat atau mendefinisikan sebuah variabel dengan assignment sebagai berikut:

```{r}
a=1;
a<-1;
1->a;
print(a)
```

**Vector**

```{r}
vector1 <- c(1,2,3,4,5)
print(vector1)
```

# Operator

## Penjumlahan

```{r}
1+2;
print(1+2)
```

## Pengurangan

```{r}
3-2;
print(3-2)

```

## Perkalian

```{r}
5*3

```

```{r}
1 && 1
0 && 0
2 && 3
5 && -5
F && F
```

```{r}
1 || 1
1 || -1
-1 || -1
-1 || 0
0 || 0
```

```{r}

```

## Pertemuan 3
### Operator perbandingan 
```{r}
print (1 == 0) # apakah 1 sama dengan 0 ?
print (1 != 0) # apakah 1 tidak sama dengan 0 ?
print (1 > 0)  # apakah 1 lebih besar dari 0 ?
print (1 >= 0) # apakah 1 lebih besar atau sama dengan 0 ?
print (1 < 0)  # apakah 1 lebih kecil dari 0 ?
print (1 <= 0) # apakah 1 lebih kecil atau sama dengan 0 ?
```
```{r}
!(25 && -1) || ((19 > 9) && ( 0 || 1))
```
### Sequence dan Matrix
```{r}
barisan1 = 1:10
barisan2 = seq(1,10)
print (barisan1)
print (barisan2)

barisan1 == barisan2
barisan3 = seq(1,10,2)
print(barisan3)
print(barisan3[4])
```
## cara mengambil elemen pada vektor

```{r}
print(barisan3)
print(barisan3[4])## index 4 di barisan3 = 7
print(barisan3[2]) ## index 2 di barisan3 = 2
print(barisan3[c(3,4)]) ## index 3 dan 4 di barisan3 = 5 7
```

```{r}
barisan3[4]
```
```{r}
barisan4 = seq(1,100,3)
print(barisan4)
n = length(barisan4)
print(n)

print(barisan4[seq(2,n,2)])
print(barisan4[seq(1,n,2)])
print(barisan4[seq(3,n,2)])
```


### Matriks
```{r}
data = c(10,20,30,40)
matrix(data = data, nrow = 2, ncol = 2)
matrix(data = data, nrow = 2, ncol = 2, byrow = "TRUE")
```

```{r}
data = 1 : 20
matrix(data = data, nrow = 4, ncol = 5)
matrix(1:20, nrow = 4, ncol = 5, byrow = "TRUE")
matrix(1:20,4,5,T)
matrix(data = data, nrow = 4, ncol = 5, byrow = "TRUE")
```


