---
title: "Pertemuan 1 dan 2"
output: html_notebook
---

Nama : Darma Wogisfry
NIM  : 200803008

# Pertemuan 1

## Heading 2

### Heading 3

```{r}
```

```{Assigment}
dalam R kita bisa membuat variabel atau mendefinisikan sebuah variabel seperti berikut :
```

```{r}
a = 1;
a <- 1;
1 -> a;
print (a)
```

{r} vector 1 \<- c (1,2)

{r}

## Vector

```{r}

vector1 <- c (1,2,3,4,5)
print (vector1)
```

\`\`\`

## Operator

### Penjumlahan

```{r}

5+2
```

### Perkalian

```{r}

5*2
```

\`\`\`

### Pengurangan

```{r}

5-2
```

### Pembagian

```{r}

5/2
```

**Operator Logika**

**AND (DAN)**

```{r}
1 && 1
1 && 0
0 && 1
-1 && 0
F && F
```

0 dianggap "FALSE", sedangkan selain 0 dianggap "TRUE"

T = `TRUE`

F = `FALSE`

**OR (ATAU)**

```{r}
1 || 1
0 || 1

```
## Pertemuan 3
### Operator Perbandingan 

```{r}
print (1 == 0) # apakah 1 sama dengan 0?
print (1 != 0) # apakaah 1 tidak sama dengan 0?
print (1 > 0)  # apakah 1 lebih besar dari 0?
print (1 >= 0)  # apakah 1 lebih besar atau sama dengan 0?
print (1 < 0)  # apakah 1 lebih kecil dari  0?
print (1 <= 0)  # apakah 1 lebih kecil sama dengan 0?

```
!(25 && -1) || ((19 > 9) && (0 || 1))

```{r}
!(25 && -1) || ((19 > 9) && (0 || 1))
```





### Sequence dan Matrix
```{r}
barisan1 = 1 : 10
barisan2 = seq(1,10)
print(barisan1)
print(barisan2)
barisan1==barisan2
barisan3 = seq(1,10,2)
print(barisan3)
print(barisan3[4])
print(barisan3[1])
```
## cara mengambil elemen pada vector
```{r}
print(barisan3)
print(barisan3[4]) ## index 4 di barisan3 = 7
print(barisan3[1]) ## index 1 di barisan3 = 1
print(barisan3[c(3,4)]) ## index 3 dan 4 dibarisan3 = 5 7
```
```{r}
barisan4 = seq(1,100,3)
print(barisan4)
n = length(barisan4)
print(n)
print(barisan4[seq(2,34,2)])
```


