---
title: "PERTEMUAN 4"
output: html_notebook
---

Nama : Aula Amaliatul Khairo

NIM : 200803006

# Struktur Keputusan

```{r}
x = 123
if(x%%2 == 0){
  print('Genap')
}else{
  print('Ganjil')
}


if(x>0){
  print('positif')
}else if(x == 0){
  print('netral')
}else{
  print('Negatif')
}
```

```{r}
x = as.double(readline("Masukkan nilai x : "))
if(x%%2 == 0){
  print('Genap')
}else{
  print('Ganjil')
}


if(x>0){
  print('positif')
}else if(x == 0){
  print('netral')
}else{
  print('Negatif')
}
```

# Looping / Perulangan

```{r}
for(i in 1:5){
  print(i)
}

for(i in c(2,4,6)){
  print(i)
}
```
```{r}
for(i in seq(2,15,2)){
  print(i)
}

for(i in 1:15){
  if(i %% 2 == 0){
  print(i)
  }
}

sprintf("%d = ganjil",i)
cat(1, " = ganjil\n")
```
# Contoh
```{r}

for(i in 1:50){
  if(i %% 2 == 0){
  print(sprintf("%2d = genap",i))
  }else{
  print(sprintf("%2d = ganjil",i)) 
  }
}

```
```{r}
for(angka in 1:50){
  if(angka %% 2 == 0){
  print(sprintf("%2d = genap",angka))
  cat(angka, "\t= Genap\n")
  print(paste0(angka, " = Genap"))
  }else{
  print(sprintf("%2d = ganjil",angka)) 
  }
}
```

