---
title: "Pertemuan 4"
output: html_notebook
---

Nama : Widya Sevri Devina Tobing

NIM : 200803098

# Struktur Keputusan

kurung kurawal tutup dan 'else' harus sejajar

```{r}
#x = 123
x =as.double(readline("Masukkan nilai x = "))
if(x%%2 == 0){
  print('Genap')
} else {
  print ('ganjil')
}
if(x>0){
  print('positif')
} else if(x==0){
  print('netral')
}else{
  print('negatif')
}
```

# Looping/Perulangan

```{r}
for( i in seq(2:15:2){
  print ('i')
}
  for(i in 1:15){
    if(i%%2 == 0){}
  print('i')
  }

```
contoh dengan sprintf
```{r}
for( i in 1:50){
    
    if(i%%2 == 0){
print(sprintf('%2d = Genap',i))
    }else{
     print(sprintf('%2d = Ganjil',i))
    }
}
```
contoh dengan paste0
```{r}
for( i in 1:50){
    
    if(i%%2 == 0){
print(paste0(i,' = Genap'))
    }else{
     print(paste0(i,' = Ganjil'))
    }
}
```
contoh dengan cat
```{r}
for( i in 1:50){
    if(i%%2 == 0){
    cat(i,"\t = Genap\n")
    }else{
    cat(i, "\t = Ganjil\n")
    }
}
```

