---
title: "Pertemuan 1 dan 2"
output: html_notebook
---

Nama : Yunida Romaito Purba

NIM : 200803044

# Pertemuan 1

## Assigment

```{r}
a = 1;
a <- 1;
1 -> a;
print(a)
```

##Vektor

```{r}
vektor1 <- c(1,2,3,4,5)
print(vektor1)
```

### Penjumlahan

```{r}
5 + 2
```

### Pengurangan

```{r}
```

```{r}
5 - 2
```

### Perkalian

```{r}
5 * 2
```

### Pembagian

```{r}
5 / 2
```

### Modulo(sisa bagi)

```{r}
5%%2
```

### Operator Logika

AND(DAN)

```{r}
1 && 1
1 && 0
0 && 1
0 && 0
5 && 5
-1 && 0
-1 && -1
5 && 1
T && T
F && F
```

0 dianggap "FALSE", sedangkan selain 0 dianggap "TRUE"

### OR(ATAU)

```{r}
1 || 1
1 || 0
0 || 1
0 || 0
```

## Pertemuan 3

### Operator Pembanding

```{r}
print(1 == 0) # apakah 1 sama dengan 0?
print(1 != 0) # apakah 1 tidak sama dengan 0?
print (1> 0) # apakah 1 lebih besar dari 0?
print (1>= 0) # apakah 1 lebih besar sama dengan dari 0?
print (1< 0) #apakah 1 lebih kecil dari 0?
print (1<= 0) #apakah 1 lebih kecil sama dengan dari 0?
```

!(25 && -1) \|\| ((19 \> 9) && (0 \|\| 1))

```{r}
!(25 && -1) || ((19 > 9) && (0 || 1))
```

### Squence dan Matriks

```{r}
barisan1 = 1:10
barisan2 = seq(1,10)
print(barisan1)
print(barisan2)
barisan1 == barisan2
barisan3 = seq(1,12,2)
print(barisan3)
print(barisan3[4])
```

## cara mengambil elemen pada vektor

```{r}
barisan3 = seq(1,12,2)
print(barisan3)
print(barisan3[4]) ## index 4 dibarisan3 = 7
print(barisan3[1]) ## index 1 dibarisan3 = 1
print(barisan3[c(3,4)]) ## index 3 dan 4 dibarisan3 = 5 7
```

```{r}
barisan4 = seq(1,100,3)
print(barisan4)
n = length(barisan4)
print(n)
print(barisan4[seq(2,n,2)])
```

### Matriks
```{r}
data = c(20,30,40,50)
matrix(data = data, nrow = 2, ncol = 2)
print('by row = FALSE')
matrix(data = data, nrow = 2, ncol = 2, byrow = TRUE)
print('by row = TRUE')
```

```{r}
data = 1:20
print(data)
matrix(data = data, nrow = 5, ncol = 4)  
matrix(data = data, nrow = 4, ncol = 5)   
matrix(data = data, nrow = 4, ncol = 5, byrow = TRUE)
```
```{r}
matrix(1:20,4,5,T)
```

