---
title: "Pertemuan 3"
output: html_notebook
---

Nama : Muhammad Alfian

NIM : 200803080

# Pertemuan 3

### Operator perbandingan

```{r}
print(1 == 0) #apakah 1 sama dengan 0?
print(1 != 0) #apakah 1 tidak sama dengan 0?
print(1 >  0) #apakah 1 lebih besar dari 0?
print(1 >= 0) #apakah 1 lebih besar atau sama dengan 0?
print(1 <  0) #apakah 1 lebih kecil dari 0?
print(1 <= 0) #apakah 1 lebih kecil atau sama dengan 0?

```

```{r}
!(25 && -1) || ((19 > 9) && (0 || 1))
```

### Sequence dan Matrix

```{r}
barisan1 = 1:10
print(barisan1)
barisan2 = seq(1,10)
print(barisan2)
barisan1 == barisan2
barisan3 = seq(1,10,2)
print(barisan3)
print(barisan3[4])
print(barisan3[1])
```

## Cara mengambil elemen pada vektor

```{r}
print(barisan3)
print(barisan3[4])          #index 4 di barisan3 = 7
print(barisan3[1])          #index 1 di barisan3 = 1
print(barisan3[c(3,4)])     #index 3 dan 4 di barisan3 = 5 7
print(barisan3[seq(1,5,2)])   #index 1, 3, dan 5 di barisan3 = 1 5 9

```

```{r}
barisan4 = seq(1,100,3)
print(barisan4)
n = length(barisan4)
print(n)
print(barisan4[seq(2,n,2)])
```

### Matrix

```{r}
x = 1:20
matrix(x,4,5,T)
```
